/* Wagmint catalog. Affiliate links supplied by site owner. */
window.siteContent={
categories:[
{name:'Dog Finds',icon:'🐕',color:'sage',description:'Everyday dog favorites'},
{name:'Cat Finds',icon:'🐈',color:'mint',description:'Clever picks for cats'},
{name:'Birds',icon:'🐦',color:'gold',description:'Perches, play & habitat ideas'},
{name:'Small Animals',icon:'🐇',color:'rose',description:'Rabbits, guinea pigs & more'},
{name:'Reptiles',icon:'🦎',color:'clay',description:'Habitat-friendly finds'},
{name:'Aquatics',icon:'🐠',color:'blue',description:'Aquarium care & organization'},
{name:'Pet Home & Travel',icon:'⌂',color:'sand',description:'Cleaner spaces and easier trips'}],
products:[
{title:'ChomChom Roller Pet Hair Remover and Reusable Lint Roller',category:'Dog Finds',price:'Popular pet-home find',badge:'WAGMINT PICK',color:'sage',symbol:'🐕',link:'https://amzn.to/4hSjzsH'},
{title:'Outward Hound Nina Ottosson Dog Brick Interactive Treat Puzzle Dog Toy',category:'Dog Finds',price:'Enrichment pick',badge:'PLAY SMARTER',color:'sage',symbol:'✦',link:'https://amzn.to/4wH0FZt'},
{title:'Benebone Wishbone Durable Dog Chew Toy',category:'Dog Finds',price:'Chew-time find',badge:'DOG FIND',color:'sage',symbol:'🦴',link:'https://amzn.to/4xZDVFb'},
{title:'Dexas MudBuster Portable Dog Paw Cleaner',category:'Dog Finds',price:'Cleanup favorite',badge:'USEFUL FIND',color:'sage',symbol:'🐾',link:'https://amzn.to/4xYHZW3'},
{title:'KONG Classic Dog Toy',category:'Dog Finds',price:'Classic enrichment pick',badge:'DOG FAVORITE',color:'sage',symbol:'●',link:'https://amzn.to/3UcDMzH'},
{title:'PETLIBRO Dockstream Cordless Cat Water Fountain',category:'Cat Finds',price:'Hydration find',badge:'CAT FIND',color:'mint',symbol:'💧',link:'https://amzn.to/4c5WP4K'},
{title:'Catstages Tower of Tracks Interactive 3-Tier Cat Toy',category:'Cat Finds',price:'Playtime pick',badge:'PLAY SMARTER',color:'mint',symbol:'✦',link:'https://amzn.to/4hWHrvr'},
{title:'FUKUMARU Cat Scratcher, 26.8 Inch L Shaped Cat Scratch Pad for Indoor Cats',category:'Cat Finds',price:'Scratch & lounge find',badge:'CAT HOME',color:'mint',symbol:'🐈',link:'https://amzn.to/4wIzD3O'},
{title:'Whiskertons Interactive Bird Simulation Cat Toy Set',category:'Cat Finds',price:'Interactive play find',badge:'TRENDING FIND',color:'mint',symbol:'🐦',link:'https://amzn.to/4c5EwN7'},
{title:'PETLIBRO Automatic Cat Feeder with Camera, 1080P HD & Night Vision',category:'Cat Finds',categories:['Cat Finds','Pet Home & Travel'],price:'Smart feeding find',badge:'SMART PET',color:'mint',symbol:'◉',link:'https://amzn.to/4c36NEa'},
{title:'JW Pet Company Activitoys Hol-ee Roller Bird Toy',category:'Birds',price:'Bird enrichment find',badge:'BIRD FIND',color:'gold',symbol:'🐦',link:'https://amzn.to/4giwxPq'},
{title:'Super Bird Creations Flying Trapeze Bird Toy',category:'Birds',price:'Play & perch find',badge:'BIRD FIND',color:'gold',symbol:'↗',link:'https://amzn.to/4xjBDks'},
{title:'JW Pet Insight Sand Perch Swing Bird Accessory',category:'Birds',price:'Perch accessory',badge:'BIRD FIND',color:'gold',symbol:'⌁',link:'https://amzn.to/4c6mevh'},
{title:'Lixit Quick Lock Bird Bath',category:'Birds',price:'Bird-care find',badge:'CARE FIND',color:'gold',symbol:'💧',link:'https://amzn.to/46iXaxx'},
{title:'Solar Smart Bird Feeder with Camera, 4K HDR Live Video, AI Bird IDs',category:'Birds',price:'Backyard bird-tech find',badge:'SMART FIND',color:'gold',symbol:'📷',link:'https://amzn.to/4xjBPjG'},
{title:'Oxbow Enriched Life Willow Play Cube Small Animal Toy',category:'Small Animals',price:'Enrichment find',badge:'SMALL PET',color:'rose',symbol:'🐇',link:'https://amzn.to/4c37aP4'},
{title:'Oxbow Timothy Club Bungalow Small Animal Hideout',category:'Small Animals',price:'Hideaway find',badge:'SMALL PET',color:'rose',symbol:'⌂',link:'https://amzn.to/3Ub43hS'},
{title:'Kaytee Premium Timothy Treat Hideout for Rabbits, Guinea Pigs, Large',category:'Small Animals',price:'Edible hideout find',badge:'SMALL PET',color:'rose',symbol:'🌾',link:'https://amzn.to/4irr89S'},
{title:'SunGrow Rabbit, Bunny & Guinea Pig Hay Feeder Rack Food Dispenser',category:'Small Animals',price:'Feeding find',badge:'USEFUL FIND',color:'rose',symbol:'▦',link:'https://amzn.to/4wLjgDQ'},
{title:'Small Pet Select Tiny Paws Willow Play Pack',category:'Small Animals',price:'Chew & play find',badge:'ENRICHMENT',color:'rose',symbol:'✦',link:'https://amzn.to/4xj3eC4'},
{title:'Zoo Med ReptiTemp Digital Infrared Thermometer',category:'Reptiles',price:'Habitat monitoring find',badge:'REPTILE CARE',color:'clay',symbol:'°',link:'https://amzn.to/4xkkLtP'},
{title:'Zoo Med Digital Thermometer Humidity Gauge',category:'Reptiles',price:'Habitat monitoring find',badge:'REPTILE CARE',color:'clay',symbol:'%',link:'https://amzn.to/4gpXIrD'},
{title:'REPTI ZOO Digital Thermometer Hygrometer',category:'Reptiles',price:'Temperature & humidity find',badge:'HABITAT FIND',color:'clay',symbol:'°',link:'https://amzn.to/46o8Qz2'},
{title:'Exo Terra Reptile Cave',category:'Reptiles',price:'Habitat hide find',badge:'HABITAT FIND',color:'clay',symbol:'⌂',link:'https://amzn.to/4wN1n7B'},
{title:'Zoo Med Angled Stainless Steel Feeding Tongs',category:'Reptiles',price:'Feeding tool find',badge:'CARE TOOL',color:'clay',symbol:'⌁',link:'https://amzn.to/4cAeJNe'},
{title:'Flipper FLOAT 2-in-1 Magnetic Aquarium Algae Cleaner',category:'Aquatics',price:'Tank-care find',badge:'AQUATIC FIND',color:'blue',symbol:'🐠',link:'https://amzn.to/4caZMkG'},
{title:'API Algae Scraper for Glass Aquariums',category:'Aquatics',price:'Tank cleaning find',badge:'AQUATIC CARE',color:'blue',symbol:'↻',link:'https://amzn.to/4wJ57XO'},
{title:'Aqueon Aquarium Water Changer',category:'Aquatics',price:'Maintenance find',badge:'AQUATIC CARE',color:'blue',symbol:'💧',link:'https://amzn.to/4guHTym'},
{title:'3MP 2K AI Reptile Aquarium Camera, Close-Focus Lens for Fish Tank Terrarium',category:'Aquatics',categories:['Aquatics','Reptiles'],price:'Smart monitoring find',badge:'SMART FIND',color:'blue',symbol:'📷',link:'https://amzn.to/4iqDChZ'},
{title:'Python No Spill Clean and Fill Aquarium Maintenance System',category:'Aquatics',price:'Tank maintenance find',badge:'AQUATIC CARE',color:'blue',symbol:'≈',link:'https://amzn.to/4yjsubN'},
{title:'Pet Hair Removal Glove Cat & Dog, Electrostatic Reusable Hair Remover Tool',category:'Pet Home & Travel',categories:['Pet Home & Travel','Dog Finds','Cat Finds'],price:'Pet-home cleanup find',badge:'PET HOME',color:'sand',symbol:'✋',link:'https://amzn.to/4y2oHPS'},
{title:'FURemover Original Indoor Pet Hair Rubber Broom',category:'Pet Home & Travel',price:'Cleaning find',badge:'PET HOME',color:'sand',symbol:'↻',link:'https://amzn.to/4guIobI'},
{title:'Gamma2 Vittles Vault Outback Airtight Pet Food Storage Container',category:'Pet Home & Travel',price:'Food-storage find',badge:'SMART STORAGE',color:'sand',symbol:'▦',link:'https://amzn.to/4gBN6oq'},
{title:'K&H Pet Products Bucket Booster Pet Seat',category:'Pet Home & Travel',price:'Travel find',badge:'ON THE GO',color:'sand',symbol:'🚗',link:'https://amzn.to/3UeR7Yi'},
{title:'URPOWER Dog Seat Cover Car Seat Cover for Pets',category:'Pet Home & Travel',categories:['Pet Home & Travel','Dog Finds'],price:'Car protection find',badge:'TRAVEL FIND',color:'sand',symbol:'🚗',link:'https://amzn.to/46oaaSw'}],
collections:[
{title:'New Pet Starter List',subtitle:'Useful basics to research before day one',number:'01',color:'warm'},
{title:'Small-Space Pet Living',subtitle:'Organization ideas for happier shared spaces',number:'02',color:'cool'},
{title:'Pet Travel, Simplified',subtitle:'Planning ideas for safer, easier trips',number:'03',color:'green'}],
articles:[
{title:'The new-pet checklist worth saving before bringing them home',tag:'NEW PET',read:'6 min read',color:'clay'},
{title:'How to organize pet supplies without taking over your home',tag:'PET HOME',read:'5 min read',color:'sage'},
{title:'A saveable pet-travel planning checklist for your next trip',tag:'TRAVEL',read:'4 min read',color:'gold'}]
};